version: "3.9"

services:
  agent:
    build:
        context: .
        dockerfile: Dockerfile_agent
    image: jenkins/ssh-agent:jdk11
    privileged: true
    container_name: agent
    networks:
      - jenkins
    expose:
      - 22
    environment:
       - JENKINS_AGENT_SSH_PUBKEY=${EXPORTED_JENKINS_AGENT_SSH_PUBKEY}

  jenkins:
    build: .
    image: jenkins:1.0.1
    container_name: jenkins-server
    restart: unless-stopped
    # privileged: true
    hostname: jenkinsserver
    labels:
      com.example.description: "Jenkins Server for AuroraLab test"
    networks:
      - jenkins
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
     - ~/jenkins:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_ADMIN_PASSWORD: ${EXPORTED_JENKINS_ADMIN_PASSWORD}
      JENKINS_BUILD_PASSWORD: ${JENKINS_BUILD_PASSWORD}
      JENKINS_JOB_DSL_URL: ${JENKINS_JOB_DSL_URL}
      JENKINS_AGENT_SSH_KEY: ${EXPORTED_JENKINS_AGENT_PRIVATE_SSH_KEY}
      GITHUB_TOKEN: ${EXPORTED_GITHUB_TOKEN}
      GITHUB_USERNAME: ${GITHUB_USERNAME}

networks:
  jenkins:
