jobs:
  - script: >
      job('Seed All DSL jobs') {
        description('Seed job for all DSL jobs')
        scm {
            git {
                remote {
                    url "${JENKINS_JOB_DSL_URL}"
                    credentials 'GitHub token'
                }
                branch '*/main'
                extensions {
                  cleanAfterCheckout()
                  wipeOutWorkspace()
                }
              }
        }
        triggers {
            scm('H/10 * * * *')
        }
        steps {
          dsl {
            external('jobs/*.groovy')
            removeAction('DELETE')
          }
        }
      }
